bf16: true
cutoff_len: 70000
dataset: truth
dataset_dir: "your/path/of/finetune_truth.jsonl-template.json"
ddp_timeout: 180000000
do_train: true
finetuning_type: lora
flash_attn: auto
gradient_accumulation_steps: 8
learning_rate: 5.0e-05
logging_steps: 30
lora_alpha: 16
lora_dropout: 0
lora_rank: 8
lora_target: all
lr_scheduler_type: cosine
max_grad_norm: 1.0
max_samples: 10000000
model_name_or_path: "your/path/to/base/model"
num_train_epochs: 5.0
optim: adamw_torch
output_dir: "youe/path/to/output"
packing: false
per_device_train_batch_size: 32
plot_loss: true
preprocessing_num_workers: 16
report_to: none
save_steps: 200
stage: sft
template: empty
trust_remote_code: true
warmup_steps: 0